module.exports = {
  ORDER_CREATED: "ORDER_CREATED",
  PAYMENT_SUCCESS: "PAYMENT_SUCCESS",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  ORDER_CANCELLED: "ORDER_CANCELLED",
  REFUND_INITIATED: "REFUND_INITIATED",
};